name: junit-test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v
        with:
          java-version: 16
      - name: Run JUnit test
        run: ./gradlew test